experiment_name: "full_transfer_experiment"
random_seed: 42

machine_specs:
  - complexity_class: "2-state-binary"
    machine_count: 10
    samples_per_machine: 5000
    weight: 1.0
  - complexity_class: "3-state-binary"
    machine_count: 15
    samples_per_machine: 4000
    weight: 1.1
  - complexity_class: "4-state-binary"
    machine_count: 8
    samples_per_machine: 3000
    weight: 1.3
  - complexity_class: "2-state-ternary"
    machine_count: 5
    samples_per_machine: 2000
    weight: 0.9
  - complexity_class: "3-state-ternary"
    machine_count: 3
    samples_per_machine: 1500
    weight: 1.2

sequence_spec:
  length_distribution: [100, 1000]
  total_sequences: 158500
  train_ratio: 0.7
  val_ratio: 0.15
  test_ratio: 0.15

quality_spec:
  min_state_coverage: 200
  min_transition_coverage: 100
  entropy_tolerance: 0.02
  length_diversity_threshold: 0.5

neural_format_config:
  context_length: 1024
  vocab_special_tokens: ["<PAD>", "<UNK>", "<BOS>", "<EOS>"]
  include_position_metadata: true
  batch_friendly_padding: true

output_config:
  save_raw_sequences: true
  save_neural_format: true
  save_statistical_analysis: true
  save_quality_reports: true
  compress_outputs: true