experiment_name: "small_transfer_experiment"
random_seed: 42

machine_specs:
  - complexity_class: "2-state-binary"
    machine_count: 3
    samples_per_machine: 500
    weight: 1.0
  - complexity_class: "3-state-binary"
    machine_count: 2
    samples_per_machine: 500
    weight: 1.0

sequence_spec:
  length_distribution: [20, 100]
  total_sequences: 2500
  train_ratio: 0.7
  val_ratio: 0.15
  test_ratio: 0.15

quality_spec:
  min_state_coverage: 30
  min_transition_coverage: 15
  entropy_tolerance: 0.05
  length_diversity_threshold: 0.3

neural_format_config:
  context_length: 256
  vocab_special_tokens: ["<PAD>", "<UNK>"]
  include_position_metadata: true
  batch_friendly_padding: true

output_config:
  save_raw_sequences: true
  save_neural_format: true
  save_statistical_analysis: true
  save_quality_reports: true
  compress_outputs: false