experiment_name: simple_extreme_bias_test
random_seed: 222
machine_specs:
  - complexity_class: '2-state-binary'
    machine_count: 6
    samples_per_machine: 1000
    bias_strength: 0.95
    probability_seed: 555
    topological: false
    weight: 1.0
    custom_probabilities:
      S0:
        '0': 0.98
        '1': 0.02
      S1:
        '0': 0.03
        '1': 0.97

sequence_spec:
  total_sequences: 6000
  length_distribution: [20, 80]
  train_ratio: 0.7
  val_ratio: 0.15
  test_ratio: 0.15

neural_format_config:
  context_length: 256
  batch_friendly_padding: true
  include_position_metadata: true
  vocab_special_tokens:
    - '<PAD>'
    - '<UNK>'

output_config:
  save_raw_sequences: true
  save_neural_format: true
  save_statistical_analysis: true
  save_quality_reports: true
  compress_outputs: false

quality_spec:
  entropy_tolerance: 0.2
  min_state_coverage: 20
  min_transition_coverage: 10
  length_diversity_threshold: 0.25
