experiment_name: extreme_bias_short
random_seed: 789
machine_specs:
  - complexity_class: '2-state-binary'
    machine_count: 4
    samples_per_machine: 600
    bias_strength: 0.9  # Extreme bias
    probability_seed: 999
    topological: false
    weight: 1.0
    custom_probabilities:
      S0:
        '0': 0.95
        '1': 0.05
      S1:
        '0': 0.1
        '1': 0.9
  - complexity_class: '3-state-binary'
    machine_count: 2
    samples_per_machine: 600
    bias_strength: 0.8
    probability_seed: 888
    topological: false
    weight: 1.5
    custom_probabilities:
      S0:
        '0': 0.9
        '1': 0.1
      S1:
        '0': 0.2
        '1': 0.8
      S2:
        '0': 0.85
        '1': 0.15

sequence_spec:
  total_sequences: 3600
  length_distribution: [10, 50]  # Much shorter sequences
  train_ratio: 0.7
  val_ratio: 0.15
  test_ratio: 0.15

neural_format_config:
  context_length: 256
  batch_friendly_padding: true
  include_position_metadata: true
  vocab_special_tokens:
    - '<PAD>'
    - '<UNK>'

output_config:
  save_raw_sequences: true
  save_neural_format: true
  save_statistical_analysis: true
  save_quality_reports: true
  compress_outputs: false

quality_spec:
  entropy_tolerance: 0.15
  min_state_coverage: 15
  min_transition_coverage: 8
  length_diversity_threshold: 0.3
