enumeration:
  max_states: 4  # Increase from 3 to 4 states
  alphabet: ['0', '1']
  max_machines_per_size: 10  # More machines per size

dataset:
  sequences_per_machine: 50  # 5x more sequences than small test
  sequence_length: 25  # Slightly longer sequences
  max_history_length: 12  # Slightly longer histories
  validation_split: 0.2

pytorch:
  batch_size: 32
  shuffle: true
  num_workers: 0

output:
  save_results: true
  save_path: "data/large_test"
  verbose: true