enumeration:
  max_states: 3
  alphabet: ['0', '1']  
  max_machines_per_size: 5

dataset:
  sequences_per_machine: 10
  sequence_length: 20
  max_history_length: 10
  validation_split: 0.2

pytorch:
  batch_size: 4
  shuffle: true
  num_workers: 0

output:
  save_results: true
  save_path: "data/small_test"
  verbose: true